#
# Copyright (C) 2010 Texas Instruments Incorporated - http://www.ti.com/ 
#
# 
#  Redistribution and use in source and binary forms, with or without 
#  modification, are permitted provided that the following conditions 
#  are met:
#
#    Redistributions of source code must retain the above copyright 
#    notice, this list of conditions and the following disclaimer.
#
#    Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the 
#    documentation and/or other materials provided with the   
#    distribution.
#
#    Neither the name of Texas Instruments Incorporated nor the names of
#    its contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
#  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
#  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
#  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#

#
# Locating the root directory
#
ROOT=../../../

#
# Device and EVM definitions
#
DEVICE=am335x
EVM=beaglebone

#
# Include makefile definitions. Includes compilation, linker and archiving
# options.
#
include ${ROOT}/makedefs_ti

#
# Source files
#
SOURCE=${PLATFORM_SRC}/*.c	

#
# Rules for building the source files
#
all: debug release

debug:
	mkdir -p debug
	$(CC) $(CFLAGS) -g $(SOURCE)
	$(AR) $(ARFLAGS) debug/libplatform.a *.o*
	@mv *.o* debug/
	@mkdir -p ${PLATFORM_BIN}/debug
	@cp debug/libplatform.a ${PLATFORM_BIN}/debug/libplatform.a

release:
	mkdir -p release
	$(CC) $(CFLAGS) -g -O2 $(SOURCE)
	$(AR) $(ARFLAGS) release/libplatform.a *.o*
	@mv *.o* release/
	@mkdir -p ${PLATFORM_BIN}/release
	@cp release/libplatform.a ${PLATFORM_BIN}/release/libplatform.a

#
# Rules for cleaning
#
clean:
	@rm -rf debug release ${PLATFORM_BIN}/debug ${PLATFORM_BIN}/release

clean+:
	@rm -rf debug release ${PLATFORM_BIN}/debug ${PLATFORM_BIN}/release


